volumes:
  hot-stocks-data:
    external: true
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://example_user:secret@db/hot-stocks
      WAIT_HOSTS: db:5432
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: example_user
      POSTGRES_DB: hot-stocks
    ports:
      - "15432:5432"
    volumes:
      - hot-stocks-data:/var/lib/postgresql/data
